# cython: language_level=3
"""
order_book.pyx
---------------
Week 2: The core Limit Order Book (LOB) matching engine, written in
Cython. Uses Price-Time Priority: at each price level, orders are
matched in the order they arrived (FIFO).

Static C-types (`cdef`) are used for the hot-path data so Cython can
compile this down to near-C performance and avoid Python object
overhead / the GIL inside the matching loop.

This file must be COMPILED before it can be imported from Python --
see setup.py in the same folder for the build step.
"""

import time


# ---- Order record -----------------------------------------------------------
cdef class Order:
    """A single resting limit order sitting in the book."""
    cdef public unsigned long long order_id
    cdef public str side          # 'B' or 'S'
    cdef public double price
    cdef public unsigned int quantity
    cdef public double timestamp  # arrival time, used for time-priority

    def __init__(self, unsigned long long order_id, str side, double price,
                 unsigned int quantity):
        self.order_id = order_id
        self.side = side
        self.price = price
        self.quantity = quantity
        self.timestamp = time.perf_counter()

    def __repr__(self):
        return (f"Order(id={self.order_id}, side={self.side}, "
                f"price={self.price}, qty={self.quantity})")


# ---- Matching result ----------------------------------------------------------
cdef class Trade:
    """A completed match between a buy order and a sell order."""
    cdef public unsigned long long buy_order_id
    cdef public unsigned long long sell_order_id
    cdef public double price
    cdef public unsigned int quantity

    def __init__(self, unsigned long long buy_order_id,
                 unsigned long long sell_order_id, double price,
                 unsigned int quantity):
        self.buy_order_id = buy_order_id
        self.sell_order_id = sell_order_id
        self.price = price
        self.quantity = quantity

    def __repr__(self):
        return (f"Trade(buy={self.buy_order_id}, sell={self.sell_order_id}, "
                f"price={self.price}, qty={self.quantity})")


# ---- The Limit Order Book ----------------------------------------------------
cdef class LimitOrderBook:
    """
    Maintains resting Buy and Sell orders and matches incoming orders
    against them using Price-Time Priority.

    bids: list of resting Buy orders, kept sorted highest price first
    asks: list of resting Sell orders, kept sorted lowest price first

    Within the same price, earlier `timestamp` orders are matched first
    (FIFO), which is enforced by insertion order + the sort being stable
    on price alone.
    """

    cdef public list bids   # list[Order], highest price first
    cdef public list asks   # list[Order], lowest price first
    cdef public list trades  # list[Trade], full trade history

    def __init__(self):
        self.bids = []
        self.asks = []
        self.trades = []

    # ---- internal helpers ----------------------------------------------------

    cdef void _insert_bid(self, Order order):
        # Highest price first; ties broken by earlier timestamp (FIFO).
        cdef int i = 0
        cdef int n = len(self.bids)
        while i < n and (self.bids[i].price > order.price or
                          (self.bids[i].price == order.price and
                           self.bids[i].timestamp <= order.timestamp)):
            i += 1
        self.bids.insert(i, order)

    cdef void _insert_ask(self, Order order):
        # Lowest price first; ties broken by earlier timestamp (FIFO).
        cdef int i = 0
        cdef int n = len(self.asks)
        while i < n and (self.asks[i].price < order.price or
                          (self.asks[i].price == order.price and
                           self.asks[i].timestamp <= order.timestamp)):
            i += 1
        self.asks.insert(i, order)

    # ---- public API ------------------------------------------------------------

    def submit_order(self, unsigned long long order_id, str side,
                      double price, unsigned int quantity):
        """
        Submit a new order to the book. It is matched immediately against
        the opposite side as far as possible; any unfilled remainder rests
        in the book. Returns the list of Trades generated by this order.
        """
        cdef Order incoming = Order(order_id, side, price, quantity)
        cdef list new_trades = []
        cdef Order resting
        cdef unsigned int matched_qty

        if side == "B":
            while incoming.quantity > 0 and len(self.asks) > 0 and \
                    self.asks[0].price <= incoming.price:
                resting = self.asks[0]
                matched_qty = min(incoming.quantity, resting.quantity)

                new_trades.append(Trade(
                    buy_order_id=incoming.order_id,
                    sell_order_id=resting.order_id,
                    price=resting.price,   # resting order sets the trade price
                    quantity=matched_qty,
                ))

                incoming.quantity -= matched_qty
                resting.quantity -= matched_qty
                if resting.quantity == 0:
                    self.asks.pop(0)

            if incoming.quantity > 0:
                self._insert_bid(incoming)

        elif side == "S":
            while incoming.quantity > 0 and len(self.bids) > 0 and \
                    self.bids[0].price >= incoming.price:
                resting = self.bids[0]
                matched_qty = min(incoming.quantity, resting.quantity)

                new_trades.append(Trade(
                    buy_order_id=resting.order_id,
                    sell_order_id=incoming.order_id,
                    price=resting.price,
                    quantity=matched_qty,
                ))

                incoming.quantity -= matched_qty
                resting.quantity -= matched_qty
                if resting.quantity == 0:
                    self.bids.pop(0)

            if incoming.quantity > 0:
                self._insert_ask(incoming)

        else:
            raise ValueError(f"side must be 'B' or 'S', got {side!r}")

        self.trades.extend(new_trades)
        return new_trades

    def best_bid(self):
        """Highest resting Buy price, or None if the bid side is empty."""
        return self.bids[0].price if self.bids else None

    def best_ask(self):
        """Lowest resting Sell price, or None if the ask side is empty."""
        return self.asks[0].price if self.asks else None

    def spread(self):
        """Bid/Ask spread, or None if either side is empty."""
        bb = self.best_bid()
        ba = self.best_ask()
        if bb is None or ba is None:
            return None
        return ba - bb
